export const TableData = [

    {
        name: 'IOU_TYPE',
        columns: [
            {
                name: '_Id',
                dataType: 'INTEGER',
                isPrimaryKey: true,
                autoIncrement: true,
                shouldNotAllowNull: true,
            },
            {
                name: 'IOUType_ID',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: true,
            },
            {
                name: 'Description',
                dataType: 'Text',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Status',
                dataType: 'Text',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },

        ]
    },
    {
        name: 'EMPLOYEE',
        columns: [
            {
                name: '_Id',
                dataType: 'INTEGER',
                isPrimaryKey: true,
                autoIncrement: true,
                shouldNotAllowNull: true,
            },
            {
                name: 'Emp_ID',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: true,
            },
            {
                name: 'EmpName',
                dataType: 'Text',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'EPFNo',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Designation',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'DEP_ID',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Status',
                dataType: 'Text',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },

        ]
    },
    {
        name: 'EMPLOYEE_TYPE',
        columns: [
            {
                name: '_Id',
                dataType: 'INTEGER',
                isPrimaryKey: true,
                autoIncrement: true,
                shouldNotAllowNull: true,
            },
            {
                name: 'EmpType_ID',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: true,
            },
            {
                name: 'EmpType_Name',
                dataType: 'Text',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Status',
                dataType: 'Text',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },

        ]
    },
    {
        name: 'USER',
        columns: [
            {
                name: '_Id',
                dataType: 'INTEGER',
                isPrimaryKey: true,
                autoIncrement: true,
                shouldNotAllowNull: true,
            },
            {
                name: 'USER_ID',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: true,
            },
            {
                name: 'UserName',
                dataType: 'Text',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'DisplayName',
                dataType: 'Text',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'ExternalName',
                dataType: 'Text',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Email',
                dataType: 'Text',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'RoleID',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Status',
                dataType: 'Text',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'UserRole',
                dataType: 'Text',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'DepartmentId',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'DepartmentName',
                dataType: 'Text',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'IOULimit',
                dataType: 'DOUBLE',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'SapEmpId',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'EPFNo',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },

        ]
    },
    {
        name: 'IOU',
        columns: [
            {
                name: '_Id',
                dataType: 'INTEGER',
                isPrimaryKey: true,
                autoIncrement: true,
                shouldNotAllowNull: true,
            },
            {
                name: 'IOU_ID',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: true,
            },
            {
                name: 'WebRefID',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'JobOwner_ID',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'IOU_Type',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'EmpId',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'RequestDate',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Amount',
                dataType: 'DOUBLE',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Approve_Status',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Approve_Remark',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Reject_Remark',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'CreatedBy',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'FinanceStatus',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'ApprovedBy',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'HOD',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'FirstActionBy',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'FirstActionAt',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'RIsLimit',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'AIsLimit',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'RIOULimit',
                dataType: 'DOUBLE',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'AIOULimit',
                dataType: 'DOUBLE',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'SecondActionBy',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'SecondActionAt',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Attachment_Status',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'ActionStep',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'FStatus',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'IsSync',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },

        ]
    },
    {
        name: 'IOU_SETTLEMENT',
        columns: [
            {
                name: '_Id',
                dataType: 'INTEGER',
                isPrimaryKey: true,
                autoIncrement: true,
                shouldNotAllowNull: true,
            },
            {
                name: 'IOUSettlement_ID',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: true,
            },
            {
                name: 'WebRefID',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'IOU_ID',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: true,
            },
            {
                name: 'JobOwner_ID',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'IOU_Type',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'EmpId',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'RequestDate',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Amount',
                dataType: 'DOUBLE',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Approve_Status',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Approve_Remark',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Reject_Remark',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'CreatedBy',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'ApprovedBy',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'HOD',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'FirstActionBy',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'FirstActionAt',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'RIsLimit',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'AIsLimit',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'RIOULimit',
                dataType: 'DOUBLE',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'AIOULimit',
                dataType: 'DOUBLE',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'SecondActionBy',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'SecondActionAt',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Attachment_Status',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'ActionStep',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'IsSync',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },

        ]
    },
    {
        name: 'ONE_OFF_SETTLEMENT',
        columns: [
            {
                name: '_Id',
                dataType: 'INTEGER',
                isPrimaryKey: true,
                autoIncrement: true,
                shouldNotAllowNull: true,
            },
            {
                name: 'ONEOFFSettlement_ID',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: true,
            },
            {
                name: 'WebRefID',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'JobOwner_ID',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'IOU_Type',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'EmpId',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'RequestDate',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Amount',
                dataType: 'DOUBLE',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Approve_Status',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Approve_Remark',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Reject_Remark',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'CreatedBy',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'ApprovedBy',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'HOD',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'FirstActionBy',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'FirstActionAt',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'RIsLimit',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'AIsLimit',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'RIOULimit',
                dataType: 'DOUBLE',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'AIOULimit',
                dataType: 'DOUBLE',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'SecondActionBy',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'SecondActionAt',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Attachment_Status',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'ActionStep',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'FStatus',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'IsSync',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },

        ]
    },
    {
        name: 'JOB',
        columns: [
            {
                name: '_Id',
                dataType: 'INTEGER',
                isPrimaryKey: true,
                autoIncrement: true,
                shouldNotAllowNull: true,
            },
            {
                name: 'Job_ID',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: true,
            },
            {
                name: 'Job_NO',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: true,
            },
            {
                name: 'Request_ID',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: true,
            },
            {
                name: 'JobOwner_ID',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: true,
            },
            {
                name: 'Expences_Type',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Amount',
                dataType: 'DOUBLE',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Remark',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'CreateDate',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'CreatedBy',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Status',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },

        ]
    },
    {
        name: 'EXPENSE_TYPE',
        columns: [
            {
                name: '_Id',
                dataType: 'INTEGER',
                isPrimaryKey: true,
                autoIncrement: true,
                shouldNotAllowNull: true,
            },
            {
                name: 'ExpType_ID',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: true,
            },
            {
                name: 'Description',
                dataType: 'Text',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Status',
                dataType: 'Text',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },

        ]
    },
    {
        name: 'ATTACHMENTS',
        columns: [
            {
                name: '_Id',
                dataType: 'INTEGER',
                isPrimaryKey: true,
                autoIncrement: true,
                shouldNotAllowNull: true,
            },
            {
                name: 'Request_ID',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: true,
            },
            {
                name: 'Img_url',
                dataType: 'Text',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Status',
                dataType: 'Text',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },

        ]
    },
    {
        name: 'IOU_JOBS',
        columns: [
            {
                name: '_Id',
                dataType: 'INTEGER',
                isPrimaryKey: true,
                autoIncrement: true,
                shouldNotAllowNull: true,
            },
            {
                name: 'Job_ID',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Job_NO',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: true,
            },
            {
                name: 'Request_ID',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: true,
            },
            {
                name: 'AccNo',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'CostCenter',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Resource',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'JobOwner_ID',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Expences_Type',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Amount',
                dataType: 'DOUBLE',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Remark',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'CreateDate',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'CreatedBy',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'IsSync',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },

        ]
    },
    {
        name: 'IOU_SETTLEMENT_JOBS',
        columns: [
            {
                name: '_Id',
                dataType: 'INTEGER',
                isPrimaryKey: true,
                autoIncrement: true,
                shouldNotAllowNull: true,
            },
            {
                name: 'Job_ID',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Job_NO',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: true,
            },
            {
                name: 'Request_ID',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: true,
            },
            {
                name: 'AccNo',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'CostCenter',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Resource',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'JobOwner_ID',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Expences_Type',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Requested_Amount',
                dataType: 'DOUBLE',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Amount',
                dataType: 'DOUBLE',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Remark',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'CreateDate',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'CreatedBy',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'IsSync',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'IOU_TYPEID',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'IstoEdit',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },


        ]
    },
    {
        name: 'ONE_OFF_SETTLEMENT_JOBS',
        columns: [
            {
                name: '_Id',
                dataType: 'INTEGER',
                isPrimaryKey: true,
                autoIncrement: true,
                shouldNotAllowNull: true,
            },
            {
                name: 'Job_ID',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Job_NO',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: true,
            },
            {
                name: 'Request_ID',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: true,
            },
            {
                name: 'AccNo',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'CostCenter',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Resource',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'JobOwner_ID',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Expences_Type',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Amount',
                dataType: 'DOUBLE',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Remark',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'CreateDate',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'CreatedBy',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'IsSync',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },

        ]
    },
    {
        name: 'VEHICLE_NO',
        columns: [
            {
                name: '_Id',
                dataType: 'INTEGER',
                isPrimaryKey: true,
                autoIncrement: true,
                shouldNotAllowNull: true,
            },
            {
                name: 'Vehicle_No',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: true,
            },
            {
                name: 'ResName',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'VehCostForKm',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
        ]
    },
    {
        name: 'JOB_NO',
        columns: [
            {
                name: '_Id',
                dataType: 'INTEGER',
                isPrimaryKey: true,
                autoIncrement: true,
                shouldNotAllowNull: true,
            },
            {
                name: 'DocEntry',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: true,
            },
            {
                name: 'Job_No',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: true,
            },
            {
                name: 'Title',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'CustomerName',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'JobType',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Status',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'OwnerName',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'OwnerEPFNo',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'CostCenter',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Location',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },

        ]
    },
    {
        name: 'JOB_OWNERS',
        columns: [
            {
                name: '_Id',
                dataType: 'INTEGER',
                isPrimaryKey: true,
                autoIncrement: true,
                shouldNotAllowNull: true,
            },
            {
                name: 'JobOwner_ID',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: true,
            },
            {
                name: 'Name',
                dataType: 'Text',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'IOULimit',
                dataType: 'DOUBLE',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'SapEmpId',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'EPFNo',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'DepartmentId',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'DepartmentName',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },


        ]
    },
    {
        name: 'USER_ROLLS',
        columns: [
            {
                name: '_Id',
                dataType: 'INTEGER',
                isPrimaryKey: true,
                autoIncrement: true,
                shouldNotAllowNull: true,
            },
            {
                name: 'ROLL_ID',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: true,
            },
            {
                name: 'RollName',
                dataType: 'Text',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Status',
                dataType: 'Text',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },

        ]
    },
    {
        name: 'DEPARTMENTS',
        columns: [
            {
                name: '_Id',
                dataType: 'INTEGER',
                isPrimaryKey: true,
                autoIncrement: true,
                shouldNotAllowNull: true,
            },
            {
                name: 'DepID',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: true,
            },
            {
                name: 'DepName',
                dataType: 'Text',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'CostCenter',
                dataType: 'Text',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'HODNo',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'HODName',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'isSubAuth',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'SubNo',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'SubstiveName',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Status',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },


        ]
    },
    {
        name: 'GL_ACCOUNT',
        columns: [
            {
                name: '_Id',
                dataType: 'INTEGER',
                isPrimaryKey: true,
                autoIncrement: true,
                shouldNotAllowNull: true,
            },
            {
                name: 'ID',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: true,
            },
            {
                name: 'ANALYSIS_CODE',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'GL_ACCOUNT',
                dataType: 'Text',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'TYPE',
                dataType: 'TEXT',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'JOB_RELATED',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
            {
                name: 'Code',
                dataType: 'INTEGER',
                isPrimaryKey: false,
                autoIncrement: false,
                shouldNotAllowNull: false,
            },
        ]
    },

]